### PR TITLE
Migrate rest-utils to use AK library instead of common-metrics

### PR DESCRIPTION
**Pull request by srpanwar-confluent**
Jira: https://confluentinc.atlassian.net/browse/MMA-7195

As part of our efforts to converge on a single telemetry pipelines for Cloud, Hosted Monitoring, and Proactive Support, we want to standardize on one metrics library and associated metrics collection framework.

This change is prerequisite for Telemetry Reporter work.

Verfication
- [x] Manually cloned and verified downstream components build + test passes https://confluentinc.atlassian.net/wiki/spaces/MMA/pages/1193709217/Rest-utils+metrics+migration+plan
- [x] Muckrake spot test https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3710/
- [x] Packaging job https://jenkins.confluent.io/job/confluentinc-pr/job/packaging/job/PR-741/2/
- [x] Full Muckrake test 
baseline: https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3721/console
with this change: https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3715/

### CODE REVIEW

**Comment by srpanwar-confluent** [comment]
> What's the testing strategy for this?
> 
> Probably warrants more than just building downstreams, but might be a good candidate for testing [confluentinc/jenkins-common#208](https://github.com/confluentinc/jenkins-common/pull/208)

I have made the change to include `downstream validation`.
I may have underestimated the scope. From the build error(with validation on) it looks like not all projects have migrated to use ak metrics library. I'll work with the individual team to see we can get those changes before merging this one. May/may not be possible for all the project to be fixed before this change. Anyways, I have created this page to track the migration https://confluentinc.atlassian.net/wiki/spaces/MMA/pages/1193709217/Rest-utils+metrics+migration+plan

**Comment by ewencp** [comment]
Glad I asked then! cc @xli1996 

Btw, not necessary to make the changes permanent for the downstream checks, this just seemed like a good test case for it (relatively new functionality). Eventually we'll turn it on for everything, but if you just want to test this PR, you can take any build of the PR in jenkins, do a Replay, and force it on. (Or leave as is and if you want to revert that before merge, feel free.)

In terms of other tests, good things to check are the muckrake build (if you just want to iterate relatively quickly locally to make sure downstreams build), packaging (has smoke tests to make sure things at least start running; should be pretty reliable as long as builds work but is a good sanity check), and full muckrake tests (which likely won't pass on the job due to flaky tests, but you can compare results to nightlies to see if anything looks off). If you need help with how to do any of these, ask here, or generally to the tools team.

**Comment by srpanwar-confluent** [comment]
Thanks @ewencp I'll remove the flag before checkin.
Regarding the tests, I was able to manually clone the downstream projects and verify build + test passed. All except `kafka-rest` need no change. I also added back dependencies for `common-config` and `common-metrics`  in pom.xml. Some dwonstream projects need them.
As you have suggested, I ran muckrake job (updated the repo+branch to point to my changes in `rest-utils` and `kafka-rest`) https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3710/. It passed . I am trying to figure out how to do same for `packaging` but not sure how to go about. If you can point me to the instruction. Thanks

**Comment by srpanwar-confluent** [comment]
@arrawatia let me know if should include this change as well https://github.com/confluentinc/rest-utils/compare/master...arrawatia:telemetry-reporter?expand=1#diff-64aa9920b5a3321a914eaee14ab57ecfR122

**Comment by ewencp** [comment]
For packaging, you can point to your fork for specific repos here https://github.com/confluentinc/packaging/blob/master/settings.sh#L255 and override branch here https://github.com/confluentinc/packaging/blob/master/settings.sh#L241. Then submit a DNM PR job with those changes.

**Comment by srpanwar-confluent** [comment]
@ewencp verified there us no regression by running the packaging job, muckrake build and full muckrake test. Updated the description with the links .

**Comment by arrawatia** [comment]
>@arrawatia let me know if should include this change as well https://github.com/confluentinc/rest-utils/compare/master...arrawatia:telemetry-reporter?expand=1#diff-64aa9920b5a3321a914eaee14ab57ecfR122

No. The work on MetricsContext is still a "work in progress". We will raise a separate PR for this after we finalize the API.

**Comment by arrawatia** [comment]
I tested changes on this PR with Schema Registry on my local laptop. All tests passed successfully and I was able to run it with our telemetry reporter enabled.

**Comment by srpanwar-confluent** [comment]
@xvrl  pr for kafka-rest https://github.com/confluentinc/kafka-rest/pull/651. If you can take a look. I merge both of them accordingly.

**Comment by xvrl** [comment]
@srpanwar-confluent let's do it!

**Pull request merged**
