### PR TITLE
Downgrade Jetty version to 9.4.24.v20191120 to "fix" rest-proxy tests.

### PR DESCRIPTION
**Pull request by rigelbm**
The Jetty version got recently bumped from 9.4.20.v20190813 to 9.4.26.v20200117 (https://github.com/confluentinc/rest-utils/commit/cfd2c46cdde5e53df751a1f71073bead474d0e06).

After the bump most rest-proxy tests started outputting stack-traces of the form:

```
ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper:62)
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Response.closeOutput()V
	at org.glassfish.jersey.jetty.JettyHttpContainer$ResponseWriter.commit(JettyHttpContainer.java:326)
	at org.glassfish.jersey.jetty.JettyHttpContainer$ResponseWriter.failure(JettyHttpContainer.java:359)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:436)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:862)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:892)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:848)
	at io.confluent.kafkarest.resources.v1.TopicsResource$1.onCompletion(TopicsResource.java:161)
	at io.confluent.kafkarest.resources.v1.TopicsResourceBinaryProduceTest$4.answer(TopicsResourceBinaryProduceTest.java:194)
	at org.easymock.internal.Result.answer(Result.java:133)
	at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:61)
	at org.easymock.internal.ReplayState.invoke(ReplayState.java:47)
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:101)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
	at io.confluent.kafkarest.ProducerPool$$EnhancerByCGLIB$$b334b222.produce(<generated>)
	at io.confluent.kafkarest.resources.v1.TopicsResource.produce(TopicsResource.java:134)
	at io.confluent.kafkarest.resources.v1.TopicsResource.produceBinary(TopicsResource.java:96)
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.jetty.JettyHttpContainer.handle(JettyHttpContainer.java:171)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
```

Usually followed by stack-traces of the form:

```
org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException: Closed
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:638)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:417)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.jetty.JettyHttpContainer.handle(JettyHttpContainer.java:171)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException: Closed
	at org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:725)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:749)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:200)
	at io.confluent.rest.metrics.MetricsResourceMethodApplicationListener$MetricsRequestEventListener$CountingOutputStream.write(MetricsResourceMethodApplicationListener.java:464)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:276)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2085)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1097)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:915)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:625)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
	... 32 more
```

Although the stack-traces above are outputted, the tests itself continue passing. Unfortunately, the tests are now outputting so much of these stack-traces that Maven is crasheshing mid-test:

```
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] io.confluent.kafkarest.resources.v1.TopicsResourceBinaryProduceTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

Note that the aforementioned crash only happens locally. Although Jenkins also outputs the stack-traces, Maven does not crash there.

I tracked the first stack-trace to the removal of closeOutput method in this commit (https://github.com/eclipse/jetty.project/commit/c5acf965067478784b54e2d241ec58fdb0b2c9fe). The second stack-trace seems to be related to this issue (https://github.com/eclipse/jetty.project/issues/4533).

This commit downgrades Jetty version to 9.4.24.v20191120, which does not seem to have either of the issues.

### CODE REVIEW

**Comment by ewencp** [comment]
I don't know that downgrading is really the right solution, we need to be able to continue upgrading Jetty. Do we understand why we're getting that API not found? Schema registry needed an update b/c it used that API and apparently the naming changed https://github.com/confluentinc/schema-registry/pull/1323/files, but I don't see how we'd be getting that exception from Jetty itself calling that API unless there's some version mismatch.

For reference, this update was made to stay aligned with upstream since Kafka upgraded to that version of Jetty as well. I think we manage to avoid any conflicts atm because we pull in copies of the kafka jars, but we shouldn't really rely on that.

**Comment by rigelbm** [comment]
Both Jersey version `2.30`, the one we use, (https://github.com/eclipse-ee4j/jersey/blob/2.30/containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpContainer.java#L326), and `2.30.1` (https://github.com/eclipse-ee4j/jersey/blob/2.30.1/containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpContainer.java#L326) still use the `closeOutput` method. The `jersey-container-jetty-http` artefact version `2.30` depends on version `9.4.17.v20190418` of `jetty-server` (https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-jetty-http/2.30). This method is not used directly anywhere in rest-proxy, afaict. Might be a version mismatch. Not sure. I'm kind of new to the world of Maven.

**Comment by ewencp** [comment]
Hmm, that makes me curious about the Kafka repo then and if we are not noticing errors, or for some reason we don't hit the same issue there. In fact, I thought we were on 2.30 in AK but I think that PR never got filed, so that might mean it's in even worse shape with Jersey on 2.28 but still using the updated jetty https://github.com/apache/kafka/blob/trunk/gradle/dependencies.gradle#L74

wrt maven, you could try `mvn dependency:tree` to see if we're getting some unexpected versions of dependencies. Unfortunately, if we have jetty as both direct and transitive dependency, the direct dependency version overrides the indirect but there's no simple way to actually validate they are compatible.

Do we know why the exception isn't causing actual test failures? That seems pretty worrying as well.

**Comment by rigelbm** [comment]
I traced a test to understand why it does not fail when the exception is thrown. Here is what is happening:

The test is a basic client-server test. It spins up a Jetty server, makes a HTTP request to it, and verifies the content of the response.

Internally, what Jetty does is, 1. it process the request, 2. writes the response on the channel (https://github.com/eclipse-ee4j/jersey/blob/2.30/core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java#L638), then 3. closes the channel and releases resources held (https://github.com/eclipse-ee4j/jersey/blob/2.30/core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java#L710).

Closing the channel will call commit  on the channel (https://github.com/eclipse-ee4j/jersey/blob/2.30/core-server/src/main/java/org/glassfish/jersey/server/ContainerResponse.java#L390), which will call the missing-method closeOutput (https://github.com/eclipse-ee4j/jersey/blob/2.30/containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpContainer.java#L326).

From the POV of the test, as soon as the response is written to the channel, it will receive it, verify it is correct, and succeed. The test has no way of knowing that the server crashed on post-processing.

The impact here is that the server is potentially not freeing resources held after the request is finished. Worse, there's a comment here (https://github.com/eclipse-ee4j/jersey/blob/2.30/core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java#L709) saying that for some requests, the response is only written on close (and it gives the example of gzip). So it might be that for some cases, we are not even written an answer in the channel. I assume the client would timeout the request in such case.

**Comment by ijuma** [comment]
I submitted a similar PR to Apache Kafka here https://github.com/apache/kafka/pull/8183

**Comment by ijuma** [comment]
Looks like https://github.com/eclipse/jetty.project/issues/4533 (part of Jetty 9.4.27) may fix the issue.

**Pull request merged**
