### PR TITLE
Check for URI scheme before checking URI port

### LINKED ISSUE #68: "ConfigException: Found a listener without a port" even though port is set
## Issue
Getting `ConfigException: Found a listener without a port` even though a listener with a port is clearly set.

## Steps to reproduce
Set a listener with a port, for example `confluent-registry-0.confluent-registry-listeners.default.svc.cluster.local:8081`

## Error message
```
[2017-06-12 14:20:40,890] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)
io.confluent.common.config.ConfigException: Found a listener without a port. All listeners must have a port. The listener without a port is: confluent-registry-0.confluent-registry-listeners.default.svc.cluster.local:8081
	at io.confluent.rest.Application.parseListeners(Application.java:350)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.getPortForIdentity(KafkaSchemaRegistry.java:196)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:129)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:53)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:37)
	at io.confluent.rest.Application.createServer(Application.java:149)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:43)
```

## Caused by
No sanity checking of wether a URI scheme has been provided before trying to get the URI port, see [Application.java#L382](https://github.com/confluentinc/rest-utils/blob/master/core/src/main/java/io/confluent/rest/Application.java#L382)

Quick and dirty REPL proof:
skarmavbild 2017-06-12 kl 19 36 31

### PR DESCRIPTION
**Pull request by mandrean**
Fixes #68.

### CODE REVIEW

**Comment by mandrean** [comment]
[clabot:check]

**Comment by ewencp** [comment]
ok to test

**Comment by ewencp** [comment]
I went ahead and retargeted for you, thanks for the patch!

**Comment by mandrean** [comment]
Saw this just now. Anyway, thanks @ewencp!

**Pull request merged**
