### PR TITLE
Bump version to 3.0.0-SNAPSHOT.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@miguno @ijuma @gwenshap @norwood Updating versions to clean up issues with system tests to address some issues in confluentinc/muckrake#90. Personally verified on that PR that it fixes issues w/ incompatible changes. These changes will be required for release anyway, modulo the SNAPSHOT suffix.

Requires confluentinc/common#29

**Comment by ijuma** [comment]
LGTM

**Comment by ewencp** [comment]
retest this please

**Comment by ewencp** [comment]
Sigh. Looks like Jenkins won't cooperate; have validated this locally and hopefully that will be good enough.

**Pull request merged**
