### PR TITLE
Remove stacktrace in response when server throws BadMessageException

### PR DESCRIPTION
**Pull request by trnguyencflt**
This will make the response nicer, in term of no stack trace will show up for error on server

- [x] test to show this works

### CODE REVIEW

**Review by AndrewJSchofield — COMMENTED** [review]
I'd like to see a test where the new exception mapper is invoked as a result of a REST call and then demonstrates that there's a JSON response.

**Comment by trnguyencflt** [comment]
@AndrewJSchofield I'm deploying this to a test cluster and will include the response for a REST request, would that be acceptable?

**Comment by AndrewJSchofield** [comment]
> @AndrewJSchofield I'm deploying this to a test cluster and will include the response for a REST request, would that be acceptable?

I do see that the effect of this might be to make `kafka-rest` behave better, so a test in that repo which shows the benefit of this work is acceptable.

**Comment by trnguyencflt** [comment]
@AndrewJSchofield thanks for pointing out about kafka-rest, I'm testing this with kafka-rest atm, and it turns out the error is raised at lower level than application, so using registerExceptionMappers doesn't work.

Will update this PR and raise another PR for kafka-rest once I figure out the correct error handler.

**Comment by trnguyencflt** [comment]
@AndrewJSchofield this PR should be ready to review now, I have added tests to validate that it should work (remove stack trace from error response).
Could you please have a look? thanks

**Pull request merged**
