### PR TITLE
KREST-7955 421 misdirected request if host does not match SNI

### PR DESCRIPTION
**Pull request by trnguyencflt**
This PR adds SniHandler that checks for SNI against the host of the request, if they don't match, response with 421.

This handler is controlled by configuration to turn off/on, default is disabled.
`sni.check.enabled`

[Jira ticket](https://confluentinc.atlassian.net/browse/KREST-7955)

### CODE REVIEW

**Review by msn-tldr — APPROVED** [review]
lgtm

**Review by msn-tldr — CHANGES_REQUESTED** [review]
@trnguyencflt Thinking more on it, it requires more work to be ready. This new feature should have "config" that acts as a feature-flag to safely roll this out.

**Comment by trnguyencflt** [comment]
@msn-tldr 

> This new feature should have "config" that acts as a feature-flag to safely roll this out

This will be done on the subsequent cc-spec change (when http2 enable -> enable sni check).

For this feature, it is complete on it's own code because we have a configuration to switch it on/off.

**Review by msn-tldr — APPROVED** [review]
lgtm

**Pull request merged**
