### PR TITLE
CP-140: add version.txt to share/doc

### PR DESCRIPTION
**Pull request by cotedm**

### CODE REVIEW

**Comment by hachikuji** [comment]
CLABot is totally trolling @cotedm.

**Comment by cotedm** [comment]
[clabot:check]

**Comment by cotedm** [comment]
[clabot:check]

**Comment by cotedm** [comment]
Ok I signed it.  @hachikuji that should keep CLABot down.  Can't be feeding the trolls.

**Comment by hachikuji** [comment]
LGTM (since I saw @ewencp already approve a similar patch). Just for my own knowledge, is the idea for the packaging scripts to overwrite this file?

**Comment by cotedm** [comment]
Yep that's the plan.  You'll see similar patches ending up in most of the repos and then packaging will make updates (CP-140).

**Pull request merged**
